/**
 * Cloudflare Worker entry: the Next.js app built by OpenNext, plus the two
 * daily push-notification sweeps that ran as Vercel crons (vercel.json).
 *
 * The schedules live in wrangler.jsonc (UTC, like on Vercel). Each run calls
 * the app's own /api/casino/push/send route with the shared CRON_SECRET, so
 * the sweep logic stays in one place.
 */

// @ts-ignore — generated by `opennextjs-cloudflare build`
import { default as handler } from './.open-next/worker.js';

type Env = { CRON_SECRET?: string };
type Ctx = { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void };

export default {
  fetch: handler.fetch,

  async scheduled(event: { cron: string }, env: Env, ctx: Ctx) {
    if (!env.CRON_SECRET) {
      console.error('CRON_SECRET absent: push sweep skipped');
      return;
    }
    // 07:00 UTC announces the overnight resets; 19:00 UTC warns about chests about to break.
    const slot = event.cron.startsWith('0 7 ') ? '?slot=morning' : '';
    const request = new Request(`https://internal.cron/api/casino/push/send${slot}`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(
      Promise.resolve(handler.fetch(request, env, ctx))
        .then((res: Response) => console.log(`push sweep ${slot || 'evening'}: ${res.status}`))
        .catch((err: unknown) => console.error('push sweep failed', err)),
    );
  },
};

// @ts-ignore — Durable Object classes OpenNext may export, re-exported for the runtime
export * from './.open-next/worker.js';
