import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const PROMPTS = [
  "Le chat dort sur le toit",
  "Il fait beau ce matin",
  "Je mange une pomme rouge",
  "La voiture roule vite",
  "Le ciel est tout bleu",
  "Je regarde la télé",
  "Il pleut des cordes dehors",
  "Mon ami est très gentil",
  "Le chien court dans le parc",
  "La fleur sent très bon",
  "Je vais à la plage",
  "Le livre est intéressant",
  "La musique est trop forte",
  "Je bois un café noir",
  "Le vent souffle fort",
  "La lune brille la nuit",
  "Je porte un chapeau vert",
  "Le train part à l'heure",
  "La maison est très grande",
  "Je joue au ballon",
  "Le poisson nage bien",
  "La table est mise",
  "Je fais mes devoirs",
  "Le feu brûle encore",
  "La porte est fermée",
  "Je prends une photo",
  "Le temps passe vite",
  "La rue est calme",
  "Je chante une chanson",
  "Le roi porte une couronne",
  "La reine est très belle",
  "Je danse sous la pluie",
  "Le loup hurle au loin",
  "La forêt est sombre",
  "Je marche dans la rue",
  "Le pain est tout chaud",
  "La soupe est prête",
  "Je coupe les cheveux",
  "Le verre est plein",
  "La clé est perdue",
  "Je cherche mon chemin",
  "Le mur est peint en blanc",
  "La chaise est cassée",
  "Je plante un arbre",
  "Le sac est lourd",
  "La ville est loin",
  "Je saute à la corde",
  "Le lit est confortable",
  "La nuit est noire",
  "Je rêve de toi",
  "Le matin se lève",
  "La journée commence bien",
  "Je pars en vacances",
  "Le bateau quitte le port",
  "La mer est agitée",
  "Je nage dans l'eau",
  "Le sable est chaud",
  "La montagne est haute",
  "Je grimpe au sommet",
  "Le chemin est long",
  "La route est droite",
  "Je conduis ma voiture",
  "Le moteur fait du bruit",
  "La fenêtre est ouverte",
  "Je vois le paysage",
  "Le jardin est fleuri",
  "La rose est rouge",
  "Je cueille une fleur",
  "Le parfum est doux",
  "La bougie est allumée",
  "Je souffle la flamme",
  "Le gâteau est bon",
  "La fête est finie",
  "Je rentre chez moi",
  "Le soleil se couche",
  "La lumière s'éteint",
  "Je ferme les yeux",
  "Le rêve commence",
  "La vie est belle",
  "Je suis heureux ici",
  "Le monde est vaste",
  "La terre tourne rond",
  "Je voyage loin",
  "Le ciel est immense",
  "La star est célèbre",
  "Je signe un autographe",
  "Le public applaudit",
  "La scène est grande",
  "Je joue mon rôle",
  "Le film est triste",
  "La fin est proche",
  "Je pleure un peu",
  "Le rire est communicatif",
  "La blague est drôle",
  "Je souris tout le temps",
  "Le clown est amusant",
  "La foire est bruyante",
  "Je mange une glace",
  "Le sucre est collant",
  "La main est sale",
  "Je lave mon visage",
  "Le savon mousse",
  "La serviette est douce",
  "Je sèche mes cheveux",
  "Le miroir reflète",
  "La beauté est intérieure",
  "Je pense à demain",
  "Le futur est incertain",
  "La chance sourit",
  "Je gagne le gros lot",
  "Le prix est élevé",
  "La valeur est grande",
  "Je garde le trésor",
  "Le coffre est caché",
  "La carte est ancienne",
  "Je suis le capitaine",
  "Le navire avance",
  "La voile claque",
  "Je tiens la barre",
  "Le cap est fixé",
  "La destination est belle",
  "Je suis arrivé",
  "Le voyage est fini",
  "La maison m'attend",
  "Je retrouve mes amis",
  "Le chien aboie",
  "La queue remue",
  "Je caresse sa tête",
  "Le chat ronronne",
  "La souris s'enfuit",
  "Je chasse les mouches",
  "Le moustique pique",
  "La guêpe est partie",
  "Je dors tranquille",
  "Le silence règne",
  "La paix est là"
];

function getLastWord(sentence: string): string {
  // Remove punctuation
  const clean = sentence.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g,"");
  return clean.split(' ').pop() || '';
}

export async function GET(request: NextRequest) {
  try {
    const prompt = PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
    const rhymeWith = getLastWord(prompt);

    return NextResponse.json({
      prompt,
      rhymeWith,
    });
    
  } catch (error) {
    console.error('Erreur API RhymeGuessr:', error);
    return NextResponse.json(
      { error: 'Erreur lors de la génération du jeu' },
      { status: 500 }
    );
  }
}
